[2020-08-07 22:41:59,926] | {{taskinstance.py:616}} | INFO | Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-08-04T00:00:00+00:00 [queued]>
[2020-08-07 22:42:00,057] | {{taskinstance.py:616}} | INFO | Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-08-04T00:00:00+00:00 [queued]>
[2020-08-07 22:42:00,065] | {{taskinstance.py:834}} | INFO | 
--------------------------------------------------------------------------------
[2020-08-07 22:42:00,073] | {{taskinstance.py:835}} | INFO | Starting attempt 1 of 2
[2020-08-07 22:42:00,078] | {{taskinstance.py:836}} | INFO | 
--------------------------------------------------------------------------------
[2020-08-07 22:42:00,295] | {{taskinstance.py:855}} | INFO | Executing <Task(MySqlOperator): create_mysql_table> on 2020-08-04T00:00:00+00:00
[2020-08-07 22:42:00,297] | {{base_task_runner.py:133}} | INFO | Running: ['airflow', 'run', 'store_DAG', 'create_mysql_table', '2020-08-04T00:00:00+00:00', '--job_id', '16', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/store_DAG.py', '--cfg_path', '/tmp/tmpdx6w2mau']
[2020-08-07 22:42:15,091] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table [2020-08-07 22:42:15,085] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=4271
[2020-08-07 22:42:15,403] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table /usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2020-08-07 22:42:15,403] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   """)
[2020-08-07 22:42:17,345] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table [2020-08-07 22:42:17,344] {{__init__.py:51}} INFO - Using executor LocalExecutor
[2020-08-07 22:42:22,552] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table [2020-08-07 22:42:22,539] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags/store_DAG.py
[2020-08-07 22:42:22,903] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table [2020-08-07 22:42:22,903] {{cli.py:516}} INFO - Running <TaskInstance: store_DAG.create_mysql_table 2020-08-04T00:00:00+00:00 [running]> on host 5f4c3a456296
[2020-08-07 22:42:23,084] | {{mysql_operator.py:61}} | INFO | Executing: CREATE TABLE IF NOT EXISTS clean_store_transactions(STORE_ID varchar(50), STORE_LOCATION varchar(50), PRODUCT_CATEGORY varchar(50), PRODUCT_ID int, MRP float, CP float, DISCOUNT float, SP float, DATE date);
[2020-08-07 22:42:23,126] | {{taskinstance.py:1047}} | ERROR | The conn_id `mysql_conn` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
    parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
    conn = self.get_connection(self.mysql_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
[2020-08-07 22:42:23,132] | {{taskinstance.py:1070}} | INFO | Marking task as UP_FOR_RETRY
[2020-08-07 22:42:23,177] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table Traceback (most recent call last):
[2020-08-07 22:42:23,177] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/bin/airflow", line 32, in <module>
[2020-08-07 22:42:23,178] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     args.func(args)
[2020-08-07 22:42:23,178] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2020-08-07 22:42:23,178] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     return f(*args, **kwargs)
[2020-08-07 22:42:23,179] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2020-08-07 22:42:23,179] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     _run(args, dag, ti)
[2020-08-07 22:42:23,179] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2020-08-07 22:42:23,179] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     pool=args.pool,
[2020-08-07 22:42:23,180] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2020-08-07 22:42:23,180] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     return func(*args, **kwargs)
[2020-08-07 22:42:23,181] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
[2020-08-07 22:42:23,181] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     result = task_copy.execute(context=context)
[2020-08-07 22:42:23,181] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
[2020-08-07 22:42:23,182] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     parameters=self.parameters)
[2020-08-07 22:42:23,182] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
[2020-08-07 22:42:23,182] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     with closing(self.get_conn()) as conn:
[2020-08-07 22:42:23,183] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
[2020-08-07 22:42:23,183] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     conn = self.get_connection(self.mysql_conn_id)
[2020-08-07 22:42:23,183] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
[2020-08-07 22:42:23,184] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     conn = random.choice(list(cls.get_connections(conn_id)))
[2020-08-07 22:42:23,184] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
[2020-08-07 22:42:23,184] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     conns = cls._get_connections_from_db(conn_id)
[2020-08-07 22:42:23,187] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2020-08-07 22:42:23,191] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     return func(*args, **kwargs)
[2020-08-07 22:42:23,191] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
[2020-08-07 22:42:23,192] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table     "The conn_id `{0}` isn't defined".format(conn_id))
[2020-08-07 22:42:23,192] | {{base_task_runner.py:115}} | INFO | Job 16: Subtask create_mysql_table airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
[2020-08-07 22:42:24,695] | {{logging_mixin.py:95}} | INFO | [[34m2020-08-07 22:42:24,695[0m] {{[34mlocal_task_job.py:[0m172}} WARNING[0m - State of this instance has been externally set to [1mup_for_retry[0m. Taking the poison pill.[0m
[2020-08-07 22:42:24,755] | {{helpers.py:319}} | INFO | Sending Signals.SIGTERM to GPID 4271
[2020-08-07 22:42:24,943] | {{helpers.py:297}} | INFO | Process psutil.Process(pid=4271, status='terminated') (4271) terminated with exit code -15
[2020-08-07 22:42:24,944] | {{logging_mixin.py:95}} | INFO | [[34m2020-08-07 22:42:24,943[0m] {{[34mlocal_task_job.py:[0m105}} INFO[0m - Task exited with return code 0[0m
