[2020-07-30 22:02:34,958] {{taskinstance.py:616}} INFO - Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [queued]>
[2020-07-30 22:02:35,015] {{taskinstance.py:616}} INFO - Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [queued]>
[2020-07-30 22:02:35,017] {{taskinstance.py:834}} INFO - 
--------------------------------------------------------------------------------
[2020-07-30 22:02:35,021] {{taskinstance.py:835}} INFO - Starting attempt 2 of 2
[2020-07-30 22:02:35,021] {{taskinstance.py:836}} INFO - 
--------------------------------------------------------------------------------
[2020-07-30 22:02:35,049] {{taskinstance.py:855}} INFO - Executing <Task(MySqlOperator): create_mysql_table> on 2020-07-21T00:00:00+00:00
[2020-07-30 22:02:35,050] {{base_task_runner.py:133}} INFO - Running: ['airflow', 'run', 'store_DAG', 'create_mysql_table', '2020-07-21T00:00:00+00:00', '--job_id', '37', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/store_DAG.py', '--cfg_path', '/tmp/tmputh8zv_u']
[2020-07-30 22:02:40,798] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table [2020-07-30 22:02:40,798] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=7956
[2020-07-30 22:02:40,946] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table /usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2020-07-30 22:02:40,947] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   """)
[2020-07-30 22:02:42,185] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table [2020-07-30 22:02:42,182] {{__init__.py:51}} INFO - Using executor LocalExecutor
[2020-07-30 22:02:45,720] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table [2020-07-30 22:02:45,713] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags/store_DAG.py
[2020-07-30 22:02:46,115] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table [2020-07-30 22:02:46,109] {{cli.py:516}} INFO - Running <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [running]> on host 6097e8989e8b
[2020-07-30 22:02:46,243] {{mysql_operator.py:61}} INFO - Executing: CREATE TABLE IF NOT EXISTS clean_store_transactions(STORE_ID varchar(50), STORE_LOCATION varchar(50), PRODUCT_CATEGORY varchar(50), PRODUCT_ID int, MRP float, CP float, DISCOUNT float, SP float, DATE date);
[2020-07-30 22:02:46,342] {{taskinstance.py:1047}} ERROR - The conn_id `mysql_conn` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
    parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
    conn = self.get_connection(self.mysql_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
[2020-07-30 22:02:46,352] {{taskinstance.py:1076}} INFO - All retries failed; marking task as FAILED
[2020-07-30 22:02:46,425] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table Traceback (most recent call last):
[2020-07-30 22:02:46,426] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/bin/airflow", line 32, in <module>
[2020-07-30 22:02:46,426] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     args.func(args)
[2020-07-30 22:02:46,426] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2020-07-30 22:02:46,427] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     return f(*args, **kwargs)
[2020-07-30 22:02:46,427] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2020-07-30 22:02:46,427] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     _run(args, dag, ti)
[2020-07-30 22:02:46,428] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2020-07-30 22:02:46,428] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     pool=args.pool,
[2020-07-30 22:02:46,429] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2020-07-30 22:02:46,429] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     return func(*args, **kwargs)
[2020-07-30 22:02:46,430] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
[2020-07-30 22:02:46,432] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     result = task_copy.execute(context=context)
[2020-07-30 22:02:46,435] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
[2020-07-30 22:02:46,436] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     parameters=self.parameters)
[2020-07-30 22:02:46,439] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
[2020-07-30 22:02:46,440] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     with closing(self.get_conn()) as conn:
[2020-07-30 22:02:46,440] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
[2020-07-30 22:02:46,441] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     conn = self.get_connection(self.mysql_conn_id)
[2020-07-30 22:02:46,441] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
[2020-07-30 22:02:46,442] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     conn = random.choice(list(cls.get_connections(conn_id)))
[2020-07-30 22:02:46,442] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
[2020-07-30 22:02:46,443] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     conns = cls._get_connections_from_db(conn_id)
[2020-07-30 22:02:46,444] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2020-07-30 22:02:46,444] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     return func(*args, **kwargs)
[2020-07-30 22:02:46,444] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
[2020-07-30 22:02:46,445] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table     "The conn_id `{0}` isn't defined".format(conn_id))
[2020-07-30 22:02:46,445] {{base_task_runner.py:115}} INFO - Job 37: Subtask create_mysql_table airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
[2020-07-30 22:02:49,731] {{logging_mixin.py:95}} INFO - [[34m2020-07-30 22:02:49,731[0m] {{[34mlocal_task_job.py:[0m105}} INFO[0m - Task exited with return code 1[0m
[2020-08-04 20:47:02,227] {{taskinstance.py:616}} time Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [queued]>
[2020-08-04 20:47:02,606] {{taskinstance.py:616}} time Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [queued]>
[2020-08-04 20:47:02,612] {{taskinstance.py:834}} time 
--------------------------------------------------------------------------------
[2020-08-04 20:47:02,616] {{taskinstance.py:835}} time Starting attempt 2 of 2
[2020-08-04 20:47:02,618] {{taskinstance.py:836}} time 
--------------------------------------------------------------------------------
[2020-08-04 20:47:02,796] {{taskinstance.py:855}} time Executing <Task(MySqlOperator): create_mysql_table> on 2020-07-21T00:00:00+00:00
[2020-08-04 20:47:02,808] {{base_task_runner.py:133}} time Running: ['airflow', 'run', 'store_DAG', 'create_mysql_table', '2020-07-21T00:00:00+00:00', '--job_id', '30', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/store_DAG.py', '--cfg_path', '/tmp/tmp3xskrn3a']
[2020-08-04 20:47:10,233] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table [2020-08-04 20:47:10,226] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=1855
[2020-08-04 20:47:10,450] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table /usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2020-08-04 20:47:10,451] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   """)
[2020-08-04 20:47:11,287] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table [2020-08-04 20:47:11,286] {{__init__.py:51}} INFO - Using executor LocalExecutor
[2020-08-04 20:47:12,912] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table [2020-08-04 20:47:12,910] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags/store_DAG.py
[2020-08-04 20:47:13,154] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table [2020-08-04 20:47:13,153] {{cli.py:516}} INFO - Running <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [running]> on host 46a88ec199b8
[2020-08-04 20:47:13,275] {{mysql_operator.py:61}} time Executing: CREATE TABLE IF NOT EXISTS clean_store_transactions(STORE_ID varchar(50), STORE_LOCATION varchar(50), PRODUCT_CATEGORY varchar(50), PRODUCT_ID int, MRP float, CP float, DISCOUNT float, SP float, DATE date);
[2020-08-04 20:47:13,343] {{taskinstance.py:1047}} time The conn_id `mysql_conn` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
    parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
    conn = self.get_connection(self.mysql_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
[2020-08-04 20:47:13,356] {{taskinstance.py:1076}} time All retries failed; marking task as FAILED
[2020-08-04 20:47:13,442] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table Traceback (most recent call last):
[2020-08-04 20:47:13,443] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/bin/airflow", line 32, in <module>
[2020-08-04 20:47:13,444] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     args.func(args)
[2020-08-04 20:47:13,444] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2020-08-04 20:47:13,447] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     return f(*args, **kwargs)
[2020-08-04 20:47:13,448] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2020-08-04 20:47:13,449] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     _run(args, dag, ti)
[2020-08-04 20:47:13,450] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2020-08-04 20:47:13,451] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     pool=args.pool,
[2020-08-04 20:47:13,451] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2020-08-04 20:47:13,452] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     return func(*args, **kwargs)
[2020-08-04 20:47:13,453] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
[2020-08-04 20:47:13,454] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     result = task_copy.execute(context=context)
[2020-08-04 20:47:13,454] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
[2020-08-04 20:47:13,455] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     parameters=self.parameters)
[2020-08-04 20:47:13,456] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
[2020-08-04 20:47:13,457] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     with closing(self.get_conn()) as conn:
[2020-08-04 20:47:13,458] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
[2020-08-04 20:47:13,458] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     conn = self.get_connection(self.mysql_conn_id)
[2020-08-04 20:47:13,459] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
[2020-08-04 20:47:13,459] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     conn = random.choice(list(cls.get_connections(conn_id)))
[2020-08-04 20:47:13,460] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
[2020-08-04 20:47:13,460] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     conns = cls._get_connections_from_db(conn_id)
[2020-08-04 20:47:13,461] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2020-08-04 20:47:13,462] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     return func(*args, **kwargs)
[2020-08-04 20:47:13,462] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
[2020-08-04 20:47:13,463] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table     "The conn_id `{0}` isn't defined".format(conn_id))
[2020-08-04 20:47:13,463] {{base_task_runner.py:115}} time Job 30: Subtask create_mysql_table airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
[2020-08-04 20:47:16,425] {{logging_mixin.py:95}} time [[34m2020-08-04 20:47:16,424[0m] {{[34mlocal_task_job.py:[0m105}} INFO[0m - Task exited with return code 1[0m
Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [queued]>
Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [queued]>

--------------------------------------------------------------------------------
Starting attempt 2 of 2

--------------------------------------------------------------------------------
Executing <Task(MySqlOperator): create_mysql_table> on 2020-07-21T00:00:00+00:00
Running: ['airflow', 'run', 'store_DAG', 'create_mysql_table', '2020-07-21T00:00:00+00:00', '--job_id', '35', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/store_DAG.py', '--cfg_path', '/tmp/tmp35r7lf04']
Job 35: Subtask create_mysql_table [2020-08-04 20:54:26,482] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=1851
Job 35: Subtask create_mysql_table /usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
Job 35: Subtask create_mysql_table   """)
Job 35: Subtask create_mysql_table [2020-08-04 20:54:35,026] {{__init__.py:51}} INFO - Using executor LocalExecutor
Job 35: Subtask create_mysql_table [2020-08-04 20:54:52,590] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags/store_DAG.py
Job 35: Subtask create_mysql_table [2020-08-04 20:54:54,426] {{cli.py:516}} INFO - Running <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [running]> on host 6a822f9627d0
Executing: CREATE TABLE IF NOT EXISTS clean_store_transactions(STORE_ID varchar(50), STORE_LOCATION varchar(50), PRODUCT_CATEGORY varchar(50), PRODUCT_ID int, MRP float, CP float, DISCOUNT float, SP float, DATE date);
The conn_id `mysql_conn` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
    parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
    conn = self.get_connection(self.mysql_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
All retries failed; marking task as FAILED
Job 35: Subtask create_mysql_table Traceback (most recent call last):
Job 35: Subtask create_mysql_table   File "/usr/local/bin/airflow", line 32, in <module>
Job 35: Subtask create_mysql_table     args.func(args)
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
Job 35: Subtask create_mysql_table     return f(*args, **kwargs)
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
Job 35: Subtask create_mysql_table     _run(args, dag, ti)
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
Job 35: Subtask create_mysql_table     pool=args.pool,
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
Job 35: Subtask create_mysql_table     return func(*args, **kwargs)
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
Job 35: Subtask create_mysql_table     result = task_copy.execute(context=context)
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
Job 35: Subtask create_mysql_table     parameters=self.parameters)
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
Job 35: Subtask create_mysql_table     with closing(self.get_conn()) as conn:
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
Job 35: Subtask create_mysql_table     conn = self.get_connection(self.mysql_conn_id)
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
Job 35: Subtask create_mysql_table     conn = random.choice(list(cls.get_connections(conn_id)))
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
Job 35: Subtask create_mysql_table     conns = cls._get_connections_from_db(conn_id)
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
Job 35: Subtask create_mysql_table     return func(*args, **kwargs)
Job 35: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
Job 35: Subtask create_mysql_table     "The conn_id `{0}` isn't defined".format(conn_id))
Job 35: Subtask create_mysql_table airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
[[34m2020-08-04 20:54:57,458[0m] {{[34mlocal_task_job.py:[0m172}} WARNING[0m - State of this instance has been externally set to [1mfailed[0m. Taking the poison pill.[0m
Sending Signals.SIGTERM to GPID 1851
Process psutil.Process(pid=1851, status='terminated') (1851) terminated with exit code -15
[[34m2020-08-04 20:54:57,952[0m] {{[34mlocal_task_job.py:[0m105}} INFO[0m - Task exited with return code 0[0m
message ----> Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [queued]>
message ----> Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [queued]>
message ----> 
--------------------------------------------------------------------------------
message ----> Starting attempt 2 of 2
message ----> 
--------------------------------------------------------------------------------
message ----> Executing <Task(MySqlOperator): create_mysql_table> on 2020-07-21T00:00:00+00:00
message ----> Running: ['airflow', 'run', 'store_DAG', 'create_mysql_table', '2020-07-21T00:00:00+00:00', '--job_id', '38', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/store_DAG.py', '--cfg_path', '/tmp/tmpjkt1iej4']
message ----> Job 38: Subtask create_mysql_table [2020-08-04 21:12:22,385] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=2452
message ----> Job 38: Subtask create_mysql_table /usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
message ----> Job 38: Subtask create_mysql_table   """)
message ----> Job 38: Subtask create_mysql_table [2020-08-04 21:12:27,125] {{__init__.py:51}} INFO - Using executor LocalExecutor
message ----> Job 38: Subtask create_mysql_table [2020-08-04 21:12:33,141] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags/store_DAG.py
message ----> Job 38: Subtask create_mysql_table [2020-08-04 21:12:33,418] {{cli.py:516}} INFO - Running <TaskInstance: store_DAG.create_mysql_table 2020-07-21T00:00:00+00:00 [running]> on host 0885e5a330eb
message ----> Executing: CREATE TABLE IF NOT EXISTS clean_store_transactions(STORE_ID varchar(50), STORE_LOCATION varchar(50), PRODUCT_CATEGORY varchar(50), PRODUCT_ID int, MRP float, CP float, DISCOUNT float, SP float, DATE date);
message ----> The conn_id `mysql_conn` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
    parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
    conn = self.get_connection(self.mysql_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
message ----> All retries failed; marking task as FAILED
message ----> Job 38: Subtask create_mysql_table Traceback (most recent call last):
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/bin/airflow", line 32, in <module>
message ----> Job 38: Subtask create_mysql_table     args.func(args)
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
message ----> Job 38: Subtask create_mysql_table     return f(*args, **kwargs)
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
message ----> Job 38: Subtask create_mysql_table     _run(args, dag, ti)
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
message ----> Job 38: Subtask create_mysql_table     pool=args.pool,
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
message ----> Job 38: Subtask create_mysql_table     return func(*args, **kwargs)
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
message ----> Job 38: Subtask create_mysql_table     result = task_copy.execute(context=context)
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
message ----> Job 38: Subtask create_mysql_table     parameters=self.parameters)
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
message ----> Job 38: Subtask create_mysql_table     with closing(self.get_conn()) as conn:
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
message ----> Job 38: Subtask create_mysql_table     conn = self.get_connection(self.mysql_conn_id)
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
message ----> Job 38: Subtask create_mysql_table     conn = random.choice(list(cls.get_connections(conn_id)))
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
message ----> Job 38: Subtask create_mysql_table     conns = cls._get_connections_from_db(conn_id)
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
message ----> Job 38: Subtask create_mysql_table     return func(*args, **kwargs)
message ----> Job 38: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
message ----> Job 38: Subtask create_mysql_table     "The conn_id `{0}` isn't defined".format(conn_id))
message ----> Job 38: Subtask create_mysql_table airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
message ----> [[34m2020-08-04 21:12:35,733[0m] {{[34mlocal_task_job.py:[0m172}} WARNING[0m - State of this instance has been externally set to [1mfailed[0m. Taking the poison pill.[0m
message ----> Sending Signals.SIGTERM to GPID 2452
message ----> Process psutil.Process(pid=2452, status='terminated') (2452) terminated with exit code -15
message ----> [[34m2020-08-04 21:12:35,902[0m] {{[34mlocal_task_job.py:[0m105}} INFO[0m - Task exited with return code 0[0m
