[2020-07-30 22:03:12,545] {{taskinstance.py:616}} INFO - Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-25T00:00:00+00:00 [queued]>
[2020-07-30 22:03:12,646] {{taskinstance.py:616}} INFO - Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-25T00:00:00+00:00 [queued]>
[2020-07-30 22:03:12,646] {{taskinstance.py:834}} INFO - 
--------------------------------------------------------------------------------
[2020-07-30 22:03:12,647] {{taskinstance.py:835}} INFO - Starting attempt 2 of 2
[2020-07-30 22:03:12,647] {{taskinstance.py:836}} INFO - 
--------------------------------------------------------------------------------
[2020-07-30 22:03:12,706] {{taskinstance.py:855}} INFO - Executing <Task(MySqlOperator): create_mysql_table> on 2020-07-25T00:00:00+00:00
[2020-07-30 22:03:12,708] {{base_task_runner.py:133}} INFO - Running: ['airflow', 'run', 'store_DAG', 'create_mysql_table', '2020-07-25T00:00:00+00:00', '--job_id', '46', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/store_DAG.py', '--cfg_path', '/tmp/tmp0e5tdlmg']
[2020-07-30 22:03:16,079] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table [2020-07-30 22:03:16,078] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=8219
[2020-07-30 22:03:16,106] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table /usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2020-07-30 22:03:16,106] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   """)
[2020-07-30 22:03:16,416] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table [2020-07-30 22:03:16,415] {{__init__.py:51}} INFO - Using executor LocalExecutor
[2020-07-30 22:03:18,148] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table [2020-07-30 22:03:18,142] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags/store_DAG.py
[2020-07-30 22:03:18,272] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table [2020-07-30 22:03:18,272] {{cli.py:516}} INFO - Running <TaskInstance: store_DAG.create_mysql_table 2020-07-25T00:00:00+00:00 [running]> on host 6097e8989e8b
[2020-07-30 22:03:18,323] {{mysql_operator.py:61}} INFO - Executing: CREATE TABLE IF NOT EXISTS clean_store_transactions(STORE_ID varchar(50), STORE_LOCATION varchar(50), PRODUCT_CATEGORY varchar(50), PRODUCT_ID int, MRP float, CP float, DISCOUNT float, SP float, DATE date);
[2020-07-30 22:03:18,373] {{taskinstance.py:1047}} ERROR - The conn_id `mysql_conn` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
    parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
    conn = self.get_connection(self.mysql_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
[2020-07-30 22:03:18,385] {{taskinstance.py:1076}} INFO - All retries failed; marking task as FAILED
[2020-07-30 22:03:18,437] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table Traceback (most recent call last):
[2020-07-30 22:03:18,437] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/bin/airflow", line 32, in <module>
[2020-07-30 22:03:18,438] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     args.func(args)
[2020-07-30 22:03:18,438] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2020-07-30 22:03:18,439] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     return f(*args, **kwargs)
[2020-07-30 22:03:18,439] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2020-07-30 22:03:18,439] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     _run(args, dag, ti)
[2020-07-30 22:03:18,440] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2020-07-30 22:03:18,440] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     pool=args.pool,
[2020-07-30 22:03:18,440] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2020-07-30 22:03:18,441] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     return func(*args, **kwargs)
[2020-07-30 22:03:18,441] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
[2020-07-30 22:03:18,441] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     result = task_copy.execute(context=context)
[2020-07-30 22:03:18,441] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
[2020-07-30 22:03:18,442] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     parameters=self.parameters)
[2020-07-30 22:03:18,442] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
[2020-07-30 22:03:18,442] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     with closing(self.get_conn()) as conn:
[2020-07-30 22:03:18,443] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
[2020-07-30 22:03:18,443] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     conn = self.get_connection(self.mysql_conn_id)
[2020-07-30 22:03:18,444] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
[2020-07-30 22:03:18,444] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     conn = random.choice(list(cls.get_connections(conn_id)))
[2020-07-30 22:03:18,444] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
[2020-07-30 22:03:18,444] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     conns = cls._get_connections_from_db(conn_id)
[2020-07-30 22:03:18,445] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2020-07-30 22:03:18,445] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     return func(*args, **kwargs)
[2020-07-30 22:03:18,445] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
[2020-07-30 22:03:18,446] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table     "The conn_id `{0}` isn't defined".format(conn_id))
[2020-07-30 22:03:18,446] {{base_task_runner.py:115}} INFO - Job 46: Subtask create_mysql_table airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
[2020-07-30 22:03:22,421] {{logging_mixin.py:95}} INFO - [[34m2020-07-30 22:03:22,421[0m] {{[34mlocal_task_job.py:[0m105}} INFO[0m - Task exited with return code 1[0m
message ----> Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-25T00:00:00+00:00 [queued]>
message ----> Dependencies all met for <TaskInstance: store_DAG.create_mysql_table 2020-07-25T00:00:00+00:00 [queued]>
message ----> 
--------------------------------------------------------------------------------
message ----> Starting attempt 2 of 2
message ----> 
--------------------------------------------------------------------------------
message ----> Executing <Task(MySqlOperator): create_mysql_table> on 2020-07-25T00:00:00+00:00
message ----> Running: ['airflow', 'run', 'store_DAG', 'create_mysql_table', '2020-07-25T00:00:00+00:00', '--job_id', '45', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/store_DAG.py', '--cfg_path', '/tmp/tmpa39m0ga3']
message ----> Job 45: Subtask create_mysql_table [2020-08-04 21:13:08,288] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=2671
message ----> Job 45: Subtask create_mysql_table /usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
message ----> Job 45: Subtask create_mysql_table   """)
message ----> Job 45: Subtask create_mysql_table [2020-08-04 21:13:10,625] {{__init__.py:51}} INFO - Using executor LocalExecutor
message ----> Job 45: Subtask create_mysql_table [2020-08-04 21:13:20,663] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags/store_DAG.py
message ----> Job 45: Subtask create_mysql_table [2020-08-04 21:13:21,761] {{cli.py:516}} INFO - Running <TaskInstance: store_DAG.create_mysql_table 2020-07-25T00:00:00+00:00 [running]> on host 0885e5a330eb
message ----> Executing: CREATE TABLE IF NOT EXISTS clean_store_transactions(STORE_ID varchar(50), STORE_LOCATION varchar(50), PRODUCT_CATEGORY varchar(50), PRODUCT_ID int, MRP float, CP float, DISCOUNT float, SP float, DATE date);
message ----> The conn_id `mysql_conn` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
    parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
    conn = self.get_connection(self.mysql_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
message ----> All retries failed; marking task as FAILED
message ----> Job 45: Subtask create_mysql_table Traceback (most recent call last):
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/bin/airflow", line 32, in <module>
message ----> Job 45: Subtask create_mysql_table     args.func(args)
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
message ----> Job 45: Subtask create_mysql_table     return f(*args, **kwargs)
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
message ----> Job 45: Subtask create_mysql_table     _run(args, dag, ti)
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
message ----> Job 45: Subtask create_mysql_table     pool=args.pool,
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
message ----> Job 45: Subtask create_mysql_table     return func(*args, **kwargs)
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
message ----> Job 45: Subtask create_mysql_table     result = task_copy.execute(context=context)
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/operators/mysql_operator.py", line 67, in execute
message ----> Job 45: Subtask create_mysql_table     parameters=self.parameters)
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
message ----> Job 45: Subtask create_mysql_table     with closing(self.get_conn()) as conn:
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/mysql_hook.py", line 72, in get_conn
message ----> Job 45: Subtask create_mysql_table     conn = self.get_connection(self.mysql_conn_id)
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
message ----> Job 45: Subtask create_mysql_table     conn = random.choice(list(cls.get_connections(conn_id)))
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
message ----> Job 45: Subtask create_mysql_table     conns = cls._get_connections_from_db(conn_id)
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
message ----> Job 45: Subtask create_mysql_table     return func(*args, **kwargs)
message ----> Job 45: Subtask create_mysql_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
message ----> Job 45: Subtask create_mysql_table     "The conn_id `{0}` isn't defined".format(conn_id))
message ----> Job 45: Subtask create_mysql_table airflow.exceptions.AirflowException: The conn_id `mysql_conn` isn't defined
message ----> [[34m2020-08-04 21:13:25,908[0m] {{[34mlocal_task_job.py:[0m172}} WARNING[0m - State of this instance has been externally set to [1mfailed[0m. Taking the poison pill.[0m
message ----> Sending Signals.SIGTERM to GPID 2671
message ----> Process psutil.Process(pid=2671, status='terminated') (2671) terminated with exit code -15
message ----> [[34m2020-08-04 21:13:26,189[0m] {{[34mlocal_task_job.py:[0m105}} INFO[0m - Task exited with return code 0[0m
